language: ruby
sudo: required

matrix:
  include:
    - env: OSX=10.14
      os: osx
      osx_image: xcode11
      rvm: system
    - os: linux
      rvm: 2.3
  allow_failures:
    - os: linux

branches:
  only:
    - master

install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - unset DYLD_LIBRARY_PATH
  - if [ `uname` = "Linux" ]; then bash ci/setup_travis_linux.sh; fi
  - if [ `uname` = "Linux" ]; then export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"; fi
  - export HOMEBREW_DEVELOPER=1
  - export HOMEBREW_NO_AUTO_UPDATE=1
  - export HOMEBREW_FORCE_VENDOR_RUBY=1
  - export HOMEBREW_VERBOSE=1 HOMEBREW_VERBOSE_USING_DOTS=1
  - if [ `uname` = "Linux" ]; then brew update; brew install pkg-config; fi
  - mkdir -p $(brew --repo)/Library/Taps/coin-or-tools
  - ln -s "$TRAVIS_BUILD_DIR" $(brew --repo)/Library/Taps/coin-or-tools/homebrew-coinor
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/coin-or-tools/homebrew-coinor"
  - chmod 0644 $(brew --repo)/Library/Taps/coin-or-tools/homebrew-coinor/*.rb
  - umask 022
  - brew tap --repair
  - brew update
  - if [ `uname` = "Linux" ]; then brew tap linuxbrew/xorg; fi
  - if [ `uname` = "Darwin" ]; then brew cask reinstall xquartz; fi

script:
  - brew test-bot --tap=coin-or-tools/coinor;

notifications:
  email: never
